name = "fast-tek"
main = "src/worker.ts"
compatibility_date = "2024-12-01"
account_id = "e7452b39fc737014144e3b3fca412900"

[vars]
ENVIRONMENT = "production"

[assets]
directory = "./dist"
binding = "ASSETS"

[[routes]]
pattern = "fast-tek.com"
custom_domain = true

[observability.logs]
enabled = true
invocation_logs = true
